[package]
name = "bevy_sample_stg"
version = "0.1.0"
edition = "2021"

[lib]
name = "bevy_sample_stg"
path = "src/lib.rs"

[[bin]]
name = "bevy_sample_stg"
path = "src/main.rs"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", features = ["dynamic"] }
rand = "0.8"
